version: 2.1

parameters:
  affected-app:
    default: "deployment/whitelabel"
    type: string

jobs:
  whitelabel-processing:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: echo "Running whitelabel Pipeline."
workflows:
  whitelabel-workflow:
    jobs:
      - whitelabel-processing
