version: 2.1

parameters:
  setup-config-param:
    default: "Running whitelabel pipeline"
    type: string
  yml-file:
    default: "whitelabel.yml"
    type: string
  yml-path:
    default: "deployment"
    type: string

jobs:
  whitelabel-processing:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: echo "Running whitelabel Pipeline."
workflows:
  whitelabel-workflow:
    jobs:
      - whitelabel-processing
